### ISSUE TITLE
Prognostic runs fail on diagnostics array shape error

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/fv3net#1767] opened 2022-04-12 21:36 UTC
Prognostic run fails with the diagnostics manager complaining about array dimensions. I ran into this using the most current master image (commit a69bb3). The same configuration is ok running on commit c592fc8. I haven't looked into what commit in between these two causes the issue. @brianhenn has also been encountering a similar issue.

ex. in logs of `example-prog-run-diag-error-1f9cbc-limiter-on-2041892965` (edited from original pasted error, I didn't paste the initial one):

```
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 77, in <module>
    main()
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 72, in main
    diag_file.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 174, in flush
    self._sink.sink(self._current_label, data_to_sink)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 95, in sink
    self.monitor.store(quantities)
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 126, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 212, in append
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 207, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1211, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1306, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1597, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1625, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.8/dist-packages/zarr/util.py", line 519, in check_array_shape
    raise ValueError('parameter {!r}: expected array with shape {!r}, got {!r}'
ValueError: parameter 'value': expected array with shape (39, 24, 48), got (24, 24, 48)
```

**Comment by AnnaKwa** [comment] 2022-04-13 18:08
Sure: `gs://vcm-ml-scratch/annak/2022-04-12/example-prog-run-diag-error/fv3gfs_run/fv3config.yml`

I just checked the diff between the fv3config.yml for the failed run versus the one that ran ok- the only difference is that in the ml model sections the errored one has the line `use_mse_conserving_humidity_limiter: true`

**Comment by brianhenn** [comment] 2022-04-15 00:11
Having trouble reproducing the error I was getting now, but it was not quite the same stack trace as this. FWIW showed up on commit 2fd49ac3d8d334415911ac89187944ac96c07c36, which is after the one you mention to be working. Will keep trying to see if I can catch it.

**Comment by brianhenn** [comment] 2022-04-15 16:44
OK was able to repro.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 77, in <module>
    main()
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 66, in main
    diag_file.observe(time, diagnostics)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 147, in observe
    self.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 174, in flush
    self._sink.sink(self._current_label, data_to_sink)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 95, in sink
    self.monitor.store(quantities)
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 126, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 212, in append
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 207, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1211, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1306, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1597, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1625, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.8/dist-packages/zarr/util.py", line 519, in check_array_shape
    raise ValueError('parameter {!r}: expected array with shape {!r}, got {!r}'
ValueError: parameter 'value': expected array with shape (79, 48, 48), got (48, 48, 48)
```
when I run at C48 with momentum prognosis and:
```
ValueError: parameter 'value': expected array with shape (13, 64, 384), got (13, 64, 79)
```
when I run at C384 with momentum prognosis. 

I don't get this crash when running on the same commit without momentum prognosis. The crash occurs at 21600 seconds in at both resolutions, which is the *second* time it would be writing (or first time appending) the 3-hourly diagnostic outputs, which includes dQu and dQv, so they seem like likely culprits but I'm not positive. The different dimension mismatches at C384 and C48 are a bit of a mystery to me. 

@AnnaKwa are you sure the trace you pasted is the first error? In my case python dumps several traces in sequence, and I see one that looks like yours further down but it is presumably not the triggering error. I'll try to glean further info about which diagnostic is actually causing the crash via process of elimination, but could you confirm whether your first stack trace is the actually the same as mine?

**Comment by AnnaKwa** [comment] 2022-04-15 16:44
The difference between crashing / not crashing for me was disabling the `use_mse_conserving_humidity_limiter` on the dQ1/dQ2 model:
```
scikit_learn:
  model:
  - gs://vcm-ml-experiments/n2f-pire-subsampled-full-range/2022-03-01/nn-tq-clipped-seed-0/trained_models/tq_tendencies
  # run is ok when includes the below false flag
  use_mse_conserving_humidity_limiter: false
```
I tested this on commit 1f9cbc, full configs below.

```
# runs
gs://vcm-ml-scratch/annak/2022-04-15/example-prog-run-diag-error-1f9cbc-no-limiter-prescribed/fv3gfs_run/fv3config.yml

# crashes
gs://vcm-ml-scratch/annak/2022-04-15/example-prog-run-diag-error-1f9cbc-limiter-on/fv3gfs_run/fv3config.yml
```

**Comment by AnnaKwa** [comment] 2022-04-15 16:46
@brianhenn You're right, I have the same initial error as you.
```
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 77, in <module>
    main()
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 72, in main
    diag_file.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 174, in flush
    self._sink.sink(self._current_label, data_to_sink)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 95, in sink
    self.monitor.store(quantities)
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 126, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 212, in append
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 207, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1211, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1306, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1597, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1625, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.8/dist-packages/zarr/util.py", line 519, in check_array_shape
    raise ValueError('parameter {!r}: expected array with shape {!r}, got {!r}'
ValueError: parameter 'value': expected array with shape (39, 24, 48), got (24, 24, 48)
```

**Comment by brianhenn** [comment] 2022-04-15 16:49
Thanks for checking.

That is very weird, because I'm running on a commit before the MSE limiter was introduced, which makes me think these are two different issues, but we're getting essentially the same failure, so maybe they're both a manifestation of something else with the diags to zarr monitor data pipeline.

**Comment by brianhenn** [comment] 2022-04-15 18:20
@AnnaKwa while I'm diving more into my MRE, do you happen to know what the differences are between your config that crashes with `use_mse_conserving_humidity_limiter: True` and the integration tests on master, which passed yesterday with `use_mse_conserving_humidity_limiter: True`, e.g., `gs://vcm-ml-scratch/test-end-to-end-integration/2022-04-14/4020199-5c1a-train-diags-prog/fv3gfs_run/fv3config.yml`?

**Comment by oliverwm1** [comment] 2022-04-15 22:13
I also ran into this when updating the workflow examples. Traceback:

```
"Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 77, in <module>
    main()
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 66, in main
    diag_file.observe(time, diagnostics)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 147, in observe
    self.flush()
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 174, in flush
    self._sink.sink(self._current_label, data_to_sink)
  File "/fv3net/workflows/prognostic_c48_run/runtime/diagnostics/manager.py", line 95, in sink
    self.monitor.store(quantities)
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 126, in store
    self._writers[name].append(quantity)  # type: ignore[index]
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 212, in append
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pace/util/zarr_monitor.py", line 207, in append
    self.array[target_slice] = quantity.view[:][from_slice]
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1211, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1306, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1597, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/usr/local/lib/python3.8/dist-packages/zarr/core.py", line 1625, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/usr/local/lib/python3.8/dist-packages/zarr/util.py", line 519, in check_array_shape
    raise ValueError('parameter {!r}: expected array with shape {!r}, got {!r}'
ValueError: parameter 'value': expected array with shape (79, 48, 48), got (48, 48, 48)"
```

**Comment by AnnaKwa** [comment] 2022-04-15 22:26
> do you happen to know what the differences are between your config that crashes with use_mse_conserving_humidity_limiter: True and the integration tests on master, which passed yesterday with use_mse_conserving_humidity_limiter: True

The diff is too large to get any useful info out of imo: https://www.diffchecker.com/iogvJ3Qh

**Comment by brianhenn** [comment] 2022-04-16 00:55
No worries, thanks. I think I figured it out, various things we do in the loop (apparently the momentum tendency predictions and the outputs of the limiter?) aren't consistent in terms of dimension order across timesteps and ranks, while the zarr monitor assumes whatever dimension order it get upon initialization for a variable will be fixed. I don't really know how we didn't run into this earlier, maybe it's an xarray version thing. I have a fix that just sorts dim order in the diagnostics manager, and that got my run working. The other cases are pretty diverse so I'm hoping the fix works for them also but not sure.

**Closed** 2022-05-03 17:38 UTC
