### ISSUE TITLE
Mappm segmentation faults

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#333] opened 2020-05-16 01:31 UTC
`mappm` has been crashing with segmentation faults on some synthetic data tests as part of #313.

I can work on a MCVE, but I suspect it occurs if delp is negative.

**Comment by mcgibbon** [comment] 2022-05-12 23:37
Might be fairly easy to fix by wrapping mappm with a check for negative delp and/or nans.

**Comment by mcgibbon** [comment] 2022-05-20 20:03
I was not able to reproduce this with nans, negative pressures, nor non-monotonic pressures. Any ideas?

**Comment by mcgibbon** [comment] 2022-05-20 20:51
Started working on this and adding tests in [this PR](https://github.com/ai2cm/fv3net/pull/1854).

**Comment by mcgibbon** [comment] 2022-05-31 16:19
Closed as not reproducible.

**Closed by mcgibbon** 2022-05-31 16:19 UTC
Labels: bug
